name: Deploy .NET App to Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore BudgetFlow.API/BudgetFlow.API.csproj

    - name: Build
      run: dotnet build BudgetFlow.API/BudgetFlow.API.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish BudgetFlow.API/BudgetFlow.API.csproj -c Release -o publish

    - name: Copy files to remote server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "./publish/*"
        target: "/var/www/budgetflow-dev"
